# Dockstore config version, not pipeline version
version: 1.2
workflows:
  - name: prealnqc
    subclass: NFL
    primaryDescriptorPath: /nextflow.config
    publish: True
    authors:
      - name: Linda Xiang
        email: lxiang@oicr.on.ca
        orcid: 0000-0002-1377-1125
      - name: Edmund Su
        email: esu@oicr.on.ca
        orcid: 0000-0003-3156-176X 
    readMePath: /README.md
    topic: icgc-argo-workflows/prealnqc is a reproducible bioinformatics best-practice analysis pipeline of ICGC ARGO Pre Alignment QC Workflow for DNA/RNA Sequencing Reads.
    filters:
      branches: 
        - main
      tags:
        - /.*/
